### ISSUE TITLE
Opposite team can press cards

### ISSUE THREAD

**Issue by gudbjornv** [benjamintd/codegame.cards#62] opened 2020-11-14 23:44 UTC
When my team is playing the other team is able to press the cards, which is an issue for first time players.

(Also, 'university' is misspelled as 'univerity')

Love your game though, awesomely minimal and simplistic edition.

**Comment by benjamintd** [comment] 2021-02-26 11:20
Hi @gudbjornv, this was done by design, so that the game is unencumbered by having to switch turns (like pressing a `yield turn` button). 

I agree it's not intuitive to some players, especially ones who don't know the physical game. 

However, with some practice, I think this is the easiest way to play the game, so I'm going to close this issue. 

Thanks for raising the point though; if many other players agree, I might consider adding turns to the game.

**Closed by benjamintd** 2021-02-26 11:20 UTC
